<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-11-22T07:57:47 IST" name="Default suite" finished-at="2021-11-22T07:58:02 IST" duration-ms="15475">
    <groups>
    </groups>
    <test started-at="2021-11-22T07:57:47 IST" name="Default test" finished-at="2021-11-22T07:58:02 IST" duration-ms="15475">
      <class name="transfer.tests.TransferTests">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:transfer.tests.TransferTests@2a54a73f]" started-at="2021-11-22T07:57:47 IST" name="beforeClass" finished-at="2021-11-22T07:57:52 IST" duration-ms="5133" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="verifyTransferFunds()[pri:0, instance:transfer.tests.TransferTests@2a54a73f]" started-at="2021-11-22T07:57:52 IST" name="verifyTransferFunds" finished-at="2021-11-22T07:57:53 IST" duration-ms="1252" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at transfer.tests.TransferTests.verifyTransferFunds(TransferTests.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTransferFunds -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:transfer.tests.TransferTests@2a54a73f]" started-at="2021-11-22T07:57:53 IST" name="afterClass" finished-at="2021-11-22T07:57:53 IST" duration-ms="292" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- transfer.tests.TransferTests -->
      <class name="login.tests.LoginTests">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:login.tests.LoginTests@3bf9ce3e]" started-at="2021-11-22T07:57:53 IST" name="beforeClass" finished-at="2021-11-22T07:57:54 IST" duration-ms="1130" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="verifyInvalidPassword()[pri:0, instance:login.tests.LoginTests@3bf9ce3e]" started-at="2021-11-22T07:57:54 IST" name="verifyInvalidPassword" finished-at="2021-11-22T07:57:58 IST" duration-ms="3432" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInvalidPassword -->
        <test-method signature="verifyInvalidUsername()[pri:0, instance:login.tests.LoginTests@3bf9ce3e]" started-at="2021-11-22T07:57:58 IST" name="verifyInvalidUsername" finished-at="2021-11-22T07:57:59 IST" duration-ms="1566" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInvalidUsername -->
        <test-method signature="verifyValidCredentials()[pri:0, instance:login.tests.LoginTests@3bf9ce3e]" started-at="2021-11-22T07:57:59 IST" name="verifyValidCredentials" finished-at="2021-11-22T07:58:02 IST" duration-ms="2305" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyValidCredentials -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:login.tests.LoginTests@3bf9ce3e]" started-at="2021-11-22T07:58:02 IST" name="afterClass" finished-at="2021-11-22T07:58:02 IST" duration-ms="323" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- login.tests.LoginTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
